dataset:
     input_paths: ["data/True_prep.csv", "data/Fake_prep.csv"]
     headers: [True, True]
variables:
    target_var: "label"
    feature_var: "features"
    target_vals: [0, 1]
    text_vars: ["title", "text"]
spark:
    app_name: "modeling"
splitting:
    seed: 42
modeling:
    output_dir: "modeling/outputs"
